# Generated by Django 5.2.15 on 2026-09-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titleEn', models.CharField(blank=True, max_length=255, null=True)),
                ('titleMr', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('descriptionEn', models.TextField(blank=True, null=True)),
                ('descriptionMr', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('updatedAt', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='batchPreference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='priorKnowledge',
            field=models.TextField(blank=True, null=True),
        ),
    ]
